#!/usr/bin/env ruby

require "rubygems"
require "thor"
require "archimate"

class ArchimateCLI < Thor
  desc "map ARCHIFILE", "EXPERIMENTAL: Produce a map of diagram links to a diagram"
  def map(archifile)
    Archimate::Mapper.new.map(archifile)
  end

  desc "merge ARCHIFILE1 ARCHIFILE2", "EXPERIMENTAL: Merge two archimate files"
  def merge(archifile1, archifile2)
    Archimate::Merger.new.merge_files(archifile1, archifile2)
  end

  desc "project ARCHIFILE PROJECTFILE", "EXPERIMENTAL: Synchronize an Archi file and an MSProject XML file"
  def project(archifile, projectfile)
    Archimate::Projector.new.project(archifile, projectfile)
  end

  desc "svg ARCHIFILE", "IN DEVELOPMENT: Produce semantically meaningful SVG files from an Archi file"
  def svg(archifile)
    Archimate::Svger.new.make_svgs(archifile)
  end

  desc "dupes ARCHIFILE", "List all duplicate elements in Archi file"
  def dupes(archifile)
    Archimate::Duper.new.list_dupes(archifile)
  end

  desc "dedupe ARCHIFILE", "de-duplicate elements in Archi file"
  def dedupe(archifile)
    Archimate::Duper.new.merge(archifile)
  end

  desc "quads ARCHIFILE", "Produce a file of Quads to populate a graph database from this model"
  def quads(archifile)
    Archimate::Quads.new.from_file(archifile)
  end
end

ArchimateCLI.start(ARGV)
